VoiceMessages crashing GUHHH (#62)
* fix(VoiceMessages): NoSuchMethodError: No virtual method setPadding(I)V

* fix(VoiceMessages): Crash due to missing waveform fields